### ISSUE TITLE
Cannot open Feedback_Prize folder

### ISSUE THREAD

**Issue by ktgiahieu** [Shujun-He/Shujun-He-Feedback-Prize---Predicting-Effective-Arguments-2nd-Place-solution#4]
Thanks for the amazing solutions Shujun He.
I have a problem accessing the Feedback_Prize folder from [Shujun_solution/src/](https://github.com/Shujun-He/TeamSKT-Feedback-Prize---Predicting-Effective-Arguments-2nd-Place-solution/tree/main/Shujun_solution/src). It appears that I can see a folder with white arrow, but cannot open it. Can you check it for me?
![image](https://user-images.githubusercontent.com/42331617/190733716-5f7bacb9-8c03-431b-90d9-adb7f493ac5c.png)

**Comment by Shujun-He** [comment]
This has been fixed.
